module.exports = {
  docs: [
    {
      type: "autogenerated",
      dirName: "tutorials"
    }
  ],
  demos: [
    {
      type: "autogenerated",
      dirName: "demos"
    }
  ],
  ...require("./sidebars-api.js")
};
